#!/bin/bash

# Function to print in green
function print_green() {
    echo -e "$(tput setaf 2)$1$(tput sgr0)"
}

# Function to print in red
function print_red() {
    echo -e "$(tput setaf 1)$1$(tput sgr0)"
}

# Function to print animated progress bar
function print_progress() {
    local progress=$1
    local length=20
    local i
    printf "["
    for ((i = 0; i < length; i++)); do
        if [ $((i * 100 / length)) -le $progress ]; then
            printf "="
        else
            printf " "
        fi
    done
    printf "] %d%%\r" "$progress"
}

# Step 1: Download the latest release file
print_progress
echo
print_green "Downloading the latest release file..."
if curl -# -L -o Q.jar "http://github.com/qRX53/Q/releases/latest/download/Q.jar"; then
    print_green "Download complete."
else
    print_red "Error downloading the file. Exiting."
    exit 1
fi

# Step 2: Create the 'q' script
echo
print_green "Creating the 'q' script..."
if echo "#! /usr/bin/env java -jar" > q && cat Q.jar >> q && chmod +x q; then
    print_green "'q' script created."
else
    print_red "Error creating the 'q' script. Exiting."
    exit 1
fi

# Step 3: Move the 'q' script to /usr/local/bin
echo
print_green "Moving the 'q' script to /usr/local/bin..."
if sudo mv q /usr/local/bin/; then
    print_green "'q' script moved to /usr/local/bin."
else
    print_red "Error moving the 'q' script. Exiting."
    exit 1
fi

# Step 4: Update PATH
echo
print_green "Updating PATH..."
if echo 'export PATH="/usr/local/bin/q:$PATH"' >> ~/.bashrc && source ~/.bashrc; then
    print_green "PATH updated."
else
    print_red "Error updating PATH. Exiting."
    exit 1
fi

# All steps completed
echo
print_green "Installation complete!"

# Clean up: Remove the downloaded jar file
echo
print_green "Cleaning up..."
if rm Q.jar; then
    print_green "Clean up complete."
else
    print_red "Error cleaning up. Please remove 'Q.jar' manually."
fi

# Print next steps
echo
print_green "To get started, run: q --version"
