#!/bin/bash

# Function to print in green
function print_green() {
    echo -e "$(tput setaf 2)$1$(tput sgr0)"
}

# Function to print in red
function print_red() {
    echo -e "$(tput setaf 1)$1$(tput sgr0)"
}

# Check if 'q' or 'Q' directory exists, if yes, create a temporary folder
if [ -d "q" ] || [ -d "Q" ]; then
    TMP_DIR=$(mktemp -d -t q_temp.XXXXXX)
    cd "$TMP_DIR" || exit 1
fi

# Step 1: Download the latest release file
echo
echo "Downloading the latest release file..."
if curl -# -L -o Q.jar "http://github.com/qRX53/Q/releases/latest/download/Q.jar"; then
    print_green "Download complete."
else
    print_red "Error downloading the file. Exiting."
    exit 1
fi

# Step 2: Create the 'q' script
echo
echo "Creating the 'q' script..."
if echo "#! /usr/bin/env java -jar" > q && cat Q.jar >> q && chmod +x q; then
    print_green "'q' script created."
else
    print_red "Error creating the 'q' script. Exiting."
    exit 1
fi

# Step 3: Move the 'q' script to /usr/local/bin
echo
echo "Moving the 'q' script to /usr/local/bin..."
if sudo mv q /usr/local/bin/; then
    print_green "'q' executable moved to /usr/local/bin."
else
    print_red "Error moving the 'q' script. Exiting."
    exit 1
fi

# Step 4: Update PATH
echo
echo "Updating PATH..."

{
    export PATH="/usr/local/bin/q:$PATH"
    print_green "PATH updated."
} || {
    print_red "Failed to update path."
}

# All steps completed
echo
print_green "Installation complete!"

# Clean up: Remove the downloaded jar file
echo
echo "Cleaning up..."
if rm Q.jar; then
    print_green "Post install clean up complete."
else
    print_red "Error cleaning up. Please remove 'Q.jar' manually."
fi

# Print next steps
echo
print_green "To get started, run: q --version"
