name: Install and Verify Q

on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Java Install
        run: sudo apt-get install libc6-i386

      - name: Install Q
        run: |
          curl -sSL "https://raw.githubusercontent.com/QRX53/Q/main/dwn/install-*nix" | sudo bash
          export PATH=$PATH:$HOME/.q

      - name: Verify Q
        run: q -v
