name: Install and Test Q

on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '20'

      - name: Install Q
        run: |
          curl -sSL "https://raw.githubusercontent.com/QRX53/Q/main/dwn/install-*nix" | sudo bash
          export PATH=$PATH:$HOME/.q

      - name: Test Q installation
        run: sudo java -jar /root/.q/Q.jar
