name: Version Bump

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Bump version
        run: |
          # Get the current version
          CURRENT_VERSION=$(grep -oP 'v\d+\.\d+\.\K\d+' src/main/java/qlang/core/lang/Environment.java)

          # Increment the version
          NEW_VERSION=$((CURRENT_VERSION + 1))

          # Handle version rollover to the next minor version
          if [ "$NEW_VERSION" -gt 99 ]; then
            NEW_VERSION=1
            sed -i "s/v\d+\.\K\d+\.\d+/$NEW_VERSION.0/" src/main/java/qlang/core/lang/Environment.java
          else
            sed -i "s/v\d+\.\d+\.\K\d+/$NEW_VERSION/" src/main/java/qlang/core/lang/Environment.java
          fi

          # Commit the changes
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Bump version to $(grep -oP 'v\d+\.\d+\.\d+' src/main/java/qlang/core/lang/Environment.java)"
          git push
